//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultatEntity
    {
        public int PersonneId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> Classement { get; set; }
        public Nullable<System.TimeSpan> HeureDepart { get; set; }
        public Nullable<System.TimeSpan> HeureArrive { get; set; }
    
        public virtual RaceEntity Course { get; set; }
        public virtual PersonEntity Personne { get; set; }
    }
}
